SportStore/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Http;

namespace SportStore.Models
{
    public class Order
    {
        [HttpBindNever]
        public int Id { get; set; }
        [Required]
        public string Customer { get; set; }
        [Required]
        [HttpBindNever]
        public decimal TotalCost { get; set; }
        public ICollection<OrderLine> Lines { get; set; }
    }
}

SportStore/Controllers/OrdersController.cs
using SportStore.Models;
using SportStore.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;

namespace SportStore.Controllers
{
    public class OrdersController : ApiController
    {
        private IRepository repo;
        public OrdersController()
        {
            repo = (IRepository)GlobalConfiguration.Configuration.DependencyResolver.GetService(typeof(IRepository));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IEnumerable<Order> List()
        {
            return repo.Orders;
        }

        public async Task<IHttpActionResult> CreateOrder(Order order)
        {
            if (ModelState.IsValid)
            {
                IDictionary<int, Product> products = repo.Products
                    .Where(p => order.Lines.Select(ol => ol.ProductId)
                        .Any(id => id == p.Id)).ToDictionary(p => p.Id);

                order.TotalCost = order.Lines.Sum(ol =>
                    ol.Count * products[ol.ProductId].Price);
                await repo.SaveOrderAsync(order);
                return Ok();
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        [HttpDelete]
        [Authorize(Roles = "Admin")]
        public async Task DeleteOrder(int id)
        {
            await repo.DeleteOrderAsync(id);
        }
    }
}

SportStore/Controllers/PrepController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SportStore.Infrastructure.Identity;
using SportStore.Models;
using SportStore.Models.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SportStore.Controllers
{
    public class PrepController : Controller
    {
        IRepository repo;

        public PrepController()
        {
            repo = new ProductRepository();
        }

        // GET: Prep
        public ActionResult Index()
        {
            return View(repo.Products);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteProduct(int id)
        {
            await repo.DeleteProductAsync(id);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> SaveProduct(Product p)
        {
            await repo.SaveProductAsync(p);
            return RedirectToAction("Index");
        }

        public ActionResult Orders()
        {
            return View(repo.Orders);
        }

        public async Task<ActionResult> DeleteOrder(int id)
        {
            await repo.DeleteOrderAsync(id);
            return RedirectToAction("Orders");
        }

        public async Task<ActionResult> SaveOrder(Order order)
        {
            await repo.SaveOrderAsync(order);
            return RedirectToAction("Orders");
        }


        public async Task<ActionResult> SignIn()
        {
            IAuthenticationManager authMgr = HttpContext.GetOwinContext().Authentication;
            StoreUserManager userMgr = HttpContext.GetOwinContext().GetUserManager<StoreUserManager>();

            var user = await userMgr.FindAsync("Admin", "secret");
            authMgr.SignIn(await userMgr.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie));
            return RedirectToAction("Index");
        }

        public ActionResult SignOut()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index");
        }
    }
}

SportStore/Views/Prep/Index.cshtml
@model IEnumerable<SportStore.Models.Product>

@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary ">
    <a href="/prep/signin" class="btn btn-sm btn-primary">Sign In</a>
    <a href="/prep/signout" class="btn btn-sm btn-primary">Sign Out</a>
    User: @(HttpContext.Current.User.Identity.Name)
</div>

<div class="panel panel-primary">
    <div class="panel-heading">Products</div>
    <table class="table table-striped">
        <tr><th>ID</th><th>Name</th><th>Category</th><th>Price</th></tr>
        @foreach (var p in Model)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Name</td>
                <td>@p.Category</td>
                <td>@p.Price</td>
            </tr>
        }
    </table>
</div>

@using (Html.BeginForm("SaveProduct", "Prep"))
{
    <input type="hidden" name="Name" value="Zippy Running Shoes" />
    <input type="hidden" name="Category" value="Running" />
    <input type="hidden" name="Description" value="Set a new Record Time" />
    <input type="hidden" name="Price" value="159.99" />

    <button class="btn btn-primary" type="submit">Create</button>
    <a href="/prep/deleteproduct/2" class="btn btn-primary">Delete</a>
}

SportStore/Views/Prep/Orders.cshtml
@model IEnumerable<SportStore.Models.Order>
@{
    ViewBag.Title = "Orders";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        Orders
    </div>
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Customer</th>
            <th colspan="3"></th>
            <th>Total Cost</th>
        </tr>
        @foreach (var o in Model)
        {
            <tr>
                <td>@o.Id</td>
                <td>@o.Customer</td>
                <td colspan="3"></td>
                <td>@string.Format("{0:c}", o.TotalCost)</td>
            </tr>
            <tr>
                <th colspan="2"></th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th></th>
            </tr>
            foreach (var ol in o.Lines)
            {
                <tr>
                    <td colspan="2"></td>
                    <td>@ol.Product.Name</td>
                    <td>@ol.Count</td>
                    <td>@string.Format("{0:c}", ol.Product.Price)</td>
                    <td></td>
                </tr>
            }
        }
    </table>
</div>

@using (Html.BeginForm("SaveOrder", "Prep"))
{
    <input type="hidden" name="Customer" value="John Poet" />
    <input type="hidden" name="TotalCost" value="91" />
    <input type="hidden" name="lines[0].productid" value="6" />
    <input type="hidden" name="lines[0].count" value="1" />
    <input type="hidden" name="lines[1].productid" value="8" />
    <input type="hidden" name="lines[1].count" value="1" />

    <button class="btn btn-primary" type="submit">Create</button>
    <a href="/prep/deleteorder/2" class="btn btn-primary">Delete</a>
}