PartyInvite/Models/GuestRsp.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PartyInvite.Models
{
    public class GuestRsp
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Email { get; set; }

        [Required]
        public bool? WillAttend { get; set; }
    }
}

PartyInvite/Controllers/API/PageSizeController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Http;

namespace PartyInvite.Controllers.API
{
    public class PageSizeController : ApiController
    {
        private static string TargetUrl = "http://apress.com";
        private Logger log = LogManager.GetCurrentClassLogger();

        public async Task<long> GetPageSize(CancellationToken cToken)
        {
            using (var wc = new WebClient())
            {
                Stopwatch sw = Stopwatch.StartNew();
                var data = await wc.DownloadDataTaskAsync(TargetUrl);
                log.Info("Elapsed time: {0}ms", sw.ElapsedMilliseconds);
                return data.LongLength;
            }
        }
    }
}

PartyInvite/Controllers/API/RsvpController.cs
using PartyInvite.DAL;
using PartyInvite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace PartyInvite.Controllers.API
{
    public class RsvpController : ApiController
    {


        public IHttpActionResult GetAttendees()
        {
            return Ok<IEnumerable<GuestRsp>>(Repo.Responses.Where(x => x.WillAttend == true));
        }


        public IHttpActionResult PostResponse(GuestRsp response)
        {
            if (ModelState.IsValid)
            {
                Repo.Add(response);
                return Ok();
            }
            return BadRequest();
        }

    }
}

PartyInvite/Controllers/HomeController.cs
using PartyInvite.DAL;
using PartyInvite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PartyInvite.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Rsvp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Rsvp(GuestRsp response)
        {
            if (ModelState.IsValid)
            {
                Repo.Add(response);
                return View("Thanks", response);
            }
            else
            {
                return View();
            }
        }

        [ChildActionOnly]
        public ActionResult Attendees()
        {
            return View(Repo.Responses.Where(x => x.WillAttend == true));
        }

    }
}

PartyInvite/Views/Home/Attendees.cshtml
@model IEnumerable<PartyInvite.Models.GuestRsp>

@if (Model.Count() == 1)
{
    <p>You are the first to accept! Hurrah!</p>
}
else
{
    <p>
        Here is the list of cool people coming: @string.Join(", ",
        Model.Select(x => x.Name))
    </p>
}

PartyInvite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Party";
}
<div class="text-center" data-bind="visible:model.view() == 'welcome'">
    <h2>We're going to have an exciting party!</h2>
    <h3>And you are invited.</h3>
    @*@Html.ActionLink("RSVP Now", "Rsvp", null, new { @class = "btn btn-success" })*@
    <button class="btn btn-success" data-bind="click: showForm">RSVP Now</button>
</div>

<div data-bind="visible: model.view() == 'form'">
    <div class="panel panel-success">
        <div class="panel-heading"><h4>RSVP</h4></div>
        <div class="panel-body">
            <div class="form-group">
                <label>Your name:</label>
                <input class="form-control" data-bind="value: model.rsvp.name" />
            </div>
            <div class="form-group">
                <label>Your email:</label>
                <input class="form-control" data-bind="value: model.rsvp.email" />
            </div>
            <div class="form-group">
                <label>Will you attend?</label>
                <select class="form-control" data-bind="value: model.rsvp.willattend">
                    <option >Choose an option</option>
                    <option value="true">Yes, I'll be there</option>
                    <option value="false">No, I can't come</option>
                </select>
            </div>
            <div class="text-center">
                <button class="btn btn-success"
                        data-bind="click: sendRsvp">
                    Submit RSVP
                </button>
            </div>
        </div>
    </div>
</div>


<div data-bind="visible: model.view() == 'thanks'">
    <h1>Thank you, <span data-bind="text: model.rsvp.name()"></span>!</h1>
    <div class="lead">
        <span data-bind="visible: model.rsvp.willattend() == 'true'">
            It's great that you're coming. The drinks are already in the fridge!
            <br />
            Here is the list of cool people coming:
            <span data-bind="text: model.attendees().join(',')"></span>
        </span>
        <span data-bind="visible: model.rsvp.willattend() == 'false'">
            Sorry to hear that you can't make it, but thanks for letting us know.
        </span>
    </div>
</div>

PartyInvite/Views/Home/Rsvp.cshtml
@model PartyInvite.Models.GuestRsp

@{
    ViewBag.Title = "Rsvp";
}

<div class="panel panel-success">
    <div class="panel-heading"><h4>RSVP</h4></div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                <label>Your name:</label>
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Your email:</label>
                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Will you attend?</label>
                    @Html.DropDownListFor(x => x.WillAttend, new[] {
                                new SelectListItem() {Text = "Yes, I'll be there",
                                    Value = bool.TrueString},
                                new SelectListItem() {Text = "No, I can't come",
                                    Value = bool.FalseString}
                            }, "Choose an option", new { @class = "form-control" })
            </div>
            <div class="text-center">
                <input class="btn btn-success" type="submit" value="Submit RSVP" />
            </div>
        }
    </div>
</div>

PartyInvite/Views/Home/Thanks.cshtml
@model PartyInvite.Models.GuestRsp
@{ ViewBag.Title = "Thanks";}
<h1>Thank you, @Model.Name!</h1>
<div class="lead">
    @if (Model.WillAttend == true)
    {
        @:It's great that you're coming. The drinks are already in the fridge!
        @Html.Action("Attendees", "Home")
    }
    else
    {
        @:Sorry to hear that you can't make it, but thanks for letting us know.
    }
</div>

PartyInvite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Party Invites</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/knockout-3.1.0.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/app/rsvp.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>